name: Build and Publish

on:
  push:
    branches:
      - master
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install -g semantic-release@19 @semantic-release/git @semantic-release/changelog @semantic-release/exec -D

      - name: Semantic release
        id: semantic
        run: |
          npx semantic-release;
          echo "VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        # Disable tests while integration tests are failing
        run: ./gradlew build -x test
        env:
          VERSION: ${{ steps.semantic.outputs.VERSION }}

      - name: Publish with Gradle
        run: |
          ./gradlew generatePom;
          ./gradlew sonatypeCentralUpload;
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          VERSION: ${{ steps.semantic.outputs.VERSION }}
